name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "mmmm issue eh ok will check thaks for help :happy"
          pr-message: "Thanks for made PR will check Continuew be nice :happy"
